### PR TITLE
generalised AHD for both 2D and 3D images

### PR DESCRIPTION
**Pull request by ashkanpakzad**
Great package! It seems that the function `border_map` in `hausdorff.py` only works for 2D images when the doc string suggests it was also intended for 3D. 

Where the shift rank, e.g. ` [-1, 0]` was 2, for the 3D case it needs to be 3, e.g. ` [-1, 0, 0]`. Also, ndirs changes from 4 to 6. 

I've generalised the function to work for both 2D and 3D and added an additional unit test for the 3D case.

Also removed the `neigh` argument which had no effect.

### CODE REVIEW

**Review by muellerdo — APPROVED** [review]
Well-written code and a really nice contribution!

**Comment by muellerdo** [comment]
Hello @ashkanpakzad,

thanks for the kind words! Happy to hear that MISeval is useful in your work/research :)

Indeed, good spot. This is a missing feature.

Thanks for this wonderful PR, this is an excellent contribution and solution to this issue!

Sadly, some dependency issues arose in the latest numba version... I fixed the versioning & dependency conflicts in the latest dev branch. Could you please merge the latest development branch into your PR fork? 

Then, CI testing should be functional again.

Cheers,
Dominik

**Comment by ashkanpakzad** [comment]
Thank you! Apologies if I pointed my PR to the wrong branch. I've merged your dev branch to my fork.

Best,
Ashkan

**Comment by muellerdo** [comment]
> Apologies if I pointed my PR to the wrong branch.

No need for apologies.

CI unittesting also was fine.
Merging PR to dev and then to master for new release to PyPI.

Again, thank you for this great contribution! :)

Cheers,
Dominik

**Pull request merged**
